/*
 * Generated by tools/stamp-version.mjs — do not edit by hand.
 *
 * The trailing hash covers every shipped file, so it changes exactly when the
 * app does. Run `npm run stamp` after changing anything the service worker
 * caches; test/static.test.js fails if this is stale.
 */

export const APP_VERSION = '2026.08.12-8213b1a8';
