#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Values are public (they identify the project, they don't grant access), but
# they still live in js/sync-config.js rather than here. This scratch file
# exists only so the library can offer what you entered last time as a default;
# it is gitignored and safe to delete.
ENV_FILE=".firebase-setup.env"

cd "$(dirname "$0")/.."

# Seed the defaults from whatever js/sync-config.js already holds, so a re-run
# offers the real current values rather than a stale copy of them.
_seed() {
  local key="$1" field="$2" value
  value=$(sed -nE "s/^  ${field}: '(.*)',$/\1/p" js/sync-config.js | head -n1)
  [[ -n "$value" ]] && ! grep -qE "^${key}=" "$ENV_FILE" 2>/dev/null \
    && printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
  return 0
}
_seed FIREBASE_PROJECT_ID projectId
_seed FIREBASE_API_KEY apiKey

banner "5BX cloud backup setup"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Create a Firebase project"
say "Backups live in your own Firebase project. Nobody else's."
open_url "https://console.firebase.google.com/"
step "Click 'Create a project' (or pick an existing one you want to reuse)."
step "Name it something like '5bx'. Google Analytics is not needed — turn it off."
note "Stay on the free Spark plan. It has no card attached, so heavy or abusive"
note "use just starts failing once the daily quota is hit, rather than billing you."
step "When it finishes, the project ID is shown under the project name."
note "It is usually the name plus a few random characters, e.g. 5bx-a1b2c."
ask FIREBASE_PROJECT_ID "Paste the project ID:"

if [[ -z "${FIREBASE_PROJECT_ID}" ]]; then
  warn "no project ID given; nothing else can be configured without it"
  exit 1
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Turn on Firestore"
say "Firestore is where each save is stored, one document per person."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/firestore"
step "Click 'Create database'."
step "Choose a location near you. This cannot be changed later."
step "Start in PRODUCTION mode, not test mode."
note "Test mode would leave the database open to the world for 30 days. The"
note "rules this wizard deploys in stage 6 are the real ones; production mode"
note "denies everything until then, which is the safe way round."
pause "Press Enter once the database exists."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Turn on anonymous sign-in"
say "Every device signs in anonymously. It is a speed bump against bots, not"
say "the thing protecting your data — the unguessable pairing link is that."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/authentication/providers"
step "If you see a 'Get started' button, click it first."
step "Under 'Sign-in method', find 'Anonymous' in the provider list."
step "Open it, switch Enable on, and Save."
pause "Press Enter once Anonymous shows as Enabled."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Register the web app"
say "This produces the API key the app sends with each request."
open_url "https://console.firebase.google.com/project/${FIREBASE_PROJECT_ID}/settings/general"
step "Scroll to 'Your apps'. Click the web icon (</>) to add a web app."
step "Nickname it '5bx'. Do NOT tick 'Also set up Firebase Hosting'."
note "The app is served from GitHub Pages; Firebase Hosting would be a second,"
note "unused deploy target."
step "Register it. In the config snippet shown, copy the apiKey value."
note "It starts with AIza. It is not a secret — it identifies the project, and"
note "the security rules are what control access — so it is entered in the clear."
ask FIREBASE_API_KEY "Paste the API key:"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Write the configuration"
say "Putting both values where the app and the Firebase CLI look for them."

write_env FIREBASE_PROJECT_ID "$FIREBASE_PROJECT_ID"
write_env FIREBASE_API_KEY "$FIREBASE_API_KEY"

# Rewrite the two values in place rather than regenerating the file, so the
# comments explaining why these are safe to commit survive.
sed -i.bak -E "s|^(  projectId: ).*|\1'${FIREBASE_PROJECT_ID}',|" js/sync-config.js
sed -i.bak -E "s|^(  apiKey: ).*|\1'${FIREBASE_API_KEY}',|" js/sync-config.js
rm -f js/sync-config.js.bak
printf '  %s✓ wrote%s js/sync-config.js\n' "$GREEN" "$RESET"

cat > .firebaserc <<JSON
{
  "projects": {
    "default": "${FIREBASE_PROJECT_ID}"
  }
}
JSON
printf '  %s✓ wrote%s .firebaserc\n' "$GREEN" "$RESET"

grep -qxF '.firebase-setup.env' .gitignore 2>/dev/null \
  || printf '\n# Scratch defaults for tools/setup-sync.sh; the real values live\n# in js/sync-config.js.\n.firebase-setup.env\n' >> .gitignore

pause "Press Enter to continue."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Deploy the security rules"
say "Until these are deployed the database denies everything, and the app will"
say "report that the backup service refused the request."
note "firestore.rules grants get/create/update on one document at a time and"
note "never 'list', so knowing one pairing link never reveals any other."

if ! confirm "Deploy firestore.rules to ${FIREBASE_PROJECT_ID} now?"; then
  SKIPPED+=("deploy the rules: npx --yes firebase-tools deploy --only firestore:rules")
else
  if ! npx --yes firebase-tools projects:list >/dev/null 2>&1; then
    say "You are not signed in to the Firebase CLI yet."
    note "A browser-less login prints a URL to visit and a code to paste back."
    npx --yes firebase-tools login --no-localhost || true
  fi

  if npx --yes firebase-tools deploy --only firestore:rules --project "$FIREBASE_PROJECT_ID"; then
    printf '  %s✓ deployed%s firestore.rules\n' "$GREEN" "$RESET"
  else
    warn "the deploy did not complete"
    SKIPPED+=("deploy the rules: npx --yes firebase-tools deploy --only firestore:rules")
  fi
fi
pause "Press Enter to continue."

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Re-stamp and check"
say "js/sync-config.js just changed, so the service worker needs a new version"
say "stamp — without one, returning visitors keep the old cached copy forever."

npm run stamp
if npm test >/dev/null 2>&1; then
  printf '  %s✓ tests pass%s\n' "$GREEN" "$RESET"
else
  warn "tests failed; run 'npm test' to see why"
fi

say ""
say "Last step, and it is yours: commit and push."
note "  git add -A && git commit -m 'Point cloud backup at a real project'"
note "  git push"
note "The project ID and API key are meant to be committed. GitHub Pages serves"
note "the app straight from the repo, so an uncommitted config reaches nobody."

finish
