#!/usr/bin/env node
/*
 * Stamps a content-derived version into js/version.js and sw.js.
 *
 * Why this exists: sw.js serves every shell file cache-first out of a cache
 * named after CACHE_VERSION, and the browser only installs a new worker when
 * sw.js itself changes byte-for-byte. So shipping a change to any other file
 * WITHOUT touching sw.js means returning visitors keep the old copy forever —
 * no reload, no pull-to-refresh, and no update banner will ever dislodge it,
 * because from the browser's point of view nothing changed. That is a silent
 * failure: the deploy looks perfectly healthy and users still run old code.
 *
 * Remembering to bump a hand-written version is exactly the kind of step that
 * gets skipped, so the version is derived from the shell's contents instead,
 * and test/static.test.js re-derives it and fails if the committed stamp is
 * stale. Run `npm run stamp` after changing any shipped file.
 *
 * Zero dependencies, like everything else in tools/. Nothing here ships to the
 * browser except the one-line js/version.js it writes.
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoPath = (...parts) => join(ROOT, ...parts);

export const VERSION_FILE = 'js/version.js';
const CACHE_VERSION_RE = /const CACHE_VERSION = '[^']*';/;

/**
 * Files whose contents define the version: everything sw.js caches, plus
 * sw.js itself (it is never cached, but a change to it is still a change to
 * the app).
 *
 * './' is dropped as a duplicate of index.html, and js/version.js is excluded
 * because it *holds* the stamp — hashing it would make the stamp depend on
 * itself.
 */
function shellFiles() {
  const sw = readFileSync(repoPath('sw.js'), 'utf8');
  const listed = sw
    .match(/const SHELL_FILES = \[([\s\S]*?)\];/)[1]
    .match(/'([^']+)'/g)
    .map((quoted) => quoted.slice(1, -1))
    .filter((path) => path !== './' && path !== `./${VERSION_FILE}`)
    .map((path) => path.replace(/^\.\//, ''));
  return [...new Set([...listed, 'sw.js'])].sort();
}

/**
 * Short content hash of the shipped app.
 *
 * sw.js is hashed with its own CACHE_VERSION line blanked out; otherwise
 * writing the stamp would change the input that produced it and no fixed
 * point would exist.
 */
export function contentHash() {
  const hash = createHash('sha256');
  for (const path of shellFiles()) {
    let contents = readFileSync(repoPath(path));
    if (path === 'sw.js') {
      contents = Buffer.from(
        contents.toString('utf8').replace(CACHE_VERSION_RE, ''), 'utf8');
    }
    hash.update(path, 'utf8');
    hash.update('\0');
    hash.update(contents);
    hash.update('\0');
  }
  return hash.digest('hex').slice(0, 8);
}

/** The version currently committed in js/version.js, or null if unreadable. */
export function committedVersion() {
  try {
    const src = readFileSync(repoPath(VERSION_FILE), 'utf8');
    return src.match(/export const APP_VERSION = '([^']+)';/)?.[1] ?? null;
  } catch {
    return null;
  }
}

export const hashOf = (version) => String(version).split('-').pop();

/** Today in the local timezone, as YYYY.MM.DD. */
function datePart(date = new Date()) {
  const pad = (n) => String(n).padStart(2, '0');
  return `${date.getFullYear()}.${pad(date.getMonth() + 1)}.${pad(date.getDate())}`;
}

/**
 * Rewrite js/version.js and sw.js's CACHE_VERSION if the contents have moved
 * on. Idempotent: when the hash already matches, nothing is written and the
 * date is left alone, so re-running never churns the tree.
 *
 * @returns {{version: string, changed: boolean}}
 */
export function stamp() {
  const hash = contentHash();
  const current = committedVersion();
  const sw = readFileSync(repoPath('sw.js'), 'utf8');
  const cacheMatches = sw.includes(`const CACHE_VERSION = '${current}';`);

  if (current && hashOf(current) === hash && cacheMatches) {
    return { version: current, changed: false };
  }

  const version = `${datePart()}-${hash}`;
  writeFileSync(repoPath(VERSION_FILE),
    `/*
 * Generated by tools/stamp-version.mjs — do not edit by hand.
 *
 * The trailing hash covers every shipped file, so it changes exactly when the
 * app does. Run \`npm run stamp\` after changing anything the service worker
 * caches; test/static.test.js fails if this is stale.
 */

export const APP_VERSION = '${version}';
`);
  writeFileSync(repoPath('sw.js'),
    sw.replace(CACHE_VERSION_RE, `const CACHE_VERSION = '${version}';`));
  return { version, changed: true };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { version, changed } = stamp();
  console.log(changed
    ? `stamped ${version} (js/version.js, sw.js)`
    : `already current at ${version}`);
}
